[package]
name = "binsearchtree"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]
edition = "2018"

[features]
default = ["std"]
graphviz = ["dot", "std"]
std = []

[dependencies]
dot = { optional = true, version = "0.1" }

[dev-dependencies]
rand = "0.7"
